// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdrWwhXRhOCj4_K5lVxdDgMOULCDIQOuc',
    appId: '1:115803564064:web:733dc412522ad8e2ee7445',
    messagingSenderId: '115803564064',
    projectId: 'fluttscore',
    authDomain: 'fluttscore.firebaseapp.com',
    storageBucket: 'fluttscore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5-JxgSQcGDnQ9Mqf9Lq_Oh_Ia8E4F6w',
    appId: '1:115803564064:android:efcaeeeb66c6c059ee7445',
    messagingSenderId: '115803564064',
    projectId: 'fluttscore',
    storageBucket: 'fluttscore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwv0lHM-bbUHkcvekhAqpsJG9-FCgzfz8',
    appId: '1:115803564064:ios:d5ae05a0e45d206fee7445',
    messagingSenderId: '115803564064',
    projectId: 'fluttscore',
    storageBucket: 'fluttscore.appspot.com',
    iosClientId: '115803564064-rf42iibtk97d276enbtq2g1k685ur14h.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwv0lHM-bbUHkcvekhAqpsJG9-FCgzfz8',
    appId: '1:115803564064:ios:d5ae05a0e45d206fee7445',
    messagingSenderId: '115803564064',
    projectId: 'fluttscore',
    storageBucket: 'fluttscore.appspot.com',
    iosClientId: '115803564064-rf42iibtk97d276enbtq2g1k685ur14h.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballApp',
  );
}
